[package]
name = "veil-cli"
version = "0.1.0"
authors = ["Coda Hale <coda.hale@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
include = ["src/**/*", "../LICENSE-MIT", "../LICENSE-APACHE", "../README.md"]
description = "Stupid crypto tricks."
default-run = "veil"

[dependencies]
bunt = "0.2.8"
clap = { version = "4.3.10", features = ["deprecated", "derive"] }
clap_complete = "4.3.1"
console = "0.15.7"
rand = { version = "0.8.5", features = ["min_const_gen"] }
thiserror = "1.0.40"
veil = { path = "../veil" }

[dev-dependencies]
anyhow = "1.0.71"
xshell = "0.2.3"

[[bin]]
name = "veil"
path = "src/cli.rs"
