[package]
name = "veil-cli"
version = "0.1.0"
authors = ["Coda Hale <coda.hale@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
include = ["src/**/*", "../LICENSE-MIT", "../LICENSE-APACHE", "..README.md"]
build = "build.rs"
description = "Stupid crypto tricks."

[dependencies]
anyhow = "1"
clap = { version = "3.0.0-rc.0", features = ["derive"] }
clio = "0.1"
mimalloc = "0.1"
rpassword = "5"
veil = { version = "0.1.0", path = "../veil" }

[build-dependencies]
clap = "3.0.0-beta.5"
clap_generate = "3.0.0-beta.5"
clio = "0.1"

[dev-dependencies]
duct = "0.13"
tempfile = "3"
