[package]
name = "veil-cli"
version = "0.1.0"
authors = ["Coda Hale <coda.hale@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
clap = "2"
rand = "0.7"
rand_core = "0.5"
rpassword = "5"
veil = { path = "../veil" }
