[package]
name = "veil-cli"
version = "0.1.0"
authors = ["Coda Hale <coda.hale@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
include = ["src/**/*", "../LICENSE-MIT", "../LICENSE-APACHE", "../README.md"]
description = "Stupid crypto tricks."

[dependencies]
veil = { path = "../veil" }
anyhow = "1.0.65"
atty = "0.2.14"
clap = { version = "4.0.0-rc.3", features = ["derive"] }
clap_complete = "4.0.0-rc.1"
rand = { version = "0.8.5", features = ["min_const_gen"] }
rpassword = "7.0.0"
shell-words = "1.1.0"
unicode-normalization = "0.1.22"

[dev-dependencies]
duct = "0.13.5"
tempfile = "3.3.0"

[[bin]]
name = "veil"
path = "src/main.rs"
