[package]
name = "veil-cli"
version = "0.1.0"
authors = ["Coda Hale <coda.hale@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
include = ["src/**/*", "../LICENSE-MIT", "../LICENSE-APACHE", "../README.md"]
description = "Stupid crypto tricks."
default-run = "veil"

[dependencies]
atty = "0.2.14"
bunt = "0.2.6"
clap = { version = "4.0.18", features = ["deprecated", "derive"] }
clap_complete = "4.0.3"
console = "0.15.2"
rand = { version = "0.8.5", features = ["min_const_gen"] }
thiserror = "1.0.37"
veil = { path = "../veil" }

[dev-dependencies]
anyhow = "1.0.66"
xshell = "0.2.2"

[[bin]]
name = "veil"
path = "src/cli.rs"
