[package]
name = "veil-cli"
version = "0.1.0"
authors = ["Coda Hale <coda.hale@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
clap = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
clio = "0.1"
filedescriptor = "0.7"
rpassword = "5"
veil = { path = "../veil" }
