[package]
name = "veil"
version = "0.1.0"
authors = ["Coda Hale <coda.hale@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
include = ["src/**/*", "../LICENSE-MIT", "../LICENSE-APACHE", "..README.md"]
description = "Stupid crypto tricks."

[features]
default = []
cli = ["anyhow", "clap", "clap_generate", "clio", "mimalloc", "rpassword"]

[dependencies]
bs58 = "0.4.0"
curve25519-dalek = "3"
rand = "0.8"
strobe-rs = "0.6"
thiserror = "1"
zeroize = { version = "1", features = ["zeroize_derive"] }

# cli-only deps
anyhow = { version = "1", optional = true }
clap = { version = "3.0.0-rc.9", features = ["derive"], optional = true }
clap_generate = { version = "3.0.0-rc.9", optional = true }
clio = { version = "0.1", optional = true }
mimalloc = { version = "0.1", optional = true }
rpassword = { version = "5", optional = true }

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }
duct = "0.13"
tempfile = "3"

[[bench]]
name = "veil_bench"
harness = false

[[bin]]
name = "veil"
required-features = ["cli"]
