[package]
name = "veil"
version = "0.1.0"
authors = ["Coda Hale <coda.hale@gmail.com>"]
edition = "2018"
include = ["src/**/*", "LICENSE", "README.md"]

[dependencies]
anyhow = "1"
argh = "0.1"
base58 = "0.1.0"
clio = "0.1"
curve25519-dalek = "3"
filedescriptor = "0.7"
getrandom = "0.2"
rpassword = "5"
strobe-rs = "0.6"
thiserror = "1"
zeroize = {version = "1", features = ["zeroize_derive"]}

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }

[[bench]]
name = "veil_bench"
harness = false
