[workspace]
members = ["veil", "veil-cli", "xtask"]

[profile.release]
codegen-units = 1
lto = "fat"

[profile.dev.package.crrl]
opt-level = 3

[profile.dev.package.cyclist]
opt-level = 3

[profile.dev.package.keccak-p]
opt-level = 3
