[workspace]
members = ["benchmarks", "veil", "veil-cli", "xtask"]
resolver = "2"

[profile.release]
codegen-units = 1
lto = "fat"

[profile.dev.package.crrl]
opt-level = 3

[profile.fuzz]
inherits = "dev"
opt-level = 3
incremental = false
codegen-units = 1
