[package]
name = "veil"
version = "0.1.0"
authors = ["Coda Hale <coda.hale@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
include = ["src/**/*", "LICENSE-MIT", "LICENSE-APACHE", "README.md"]
description = "Stupid crypto tricks."

[features]
default = ["cli"]
cli = ["anyhow", "clap", "clap_complete", "clio", "mimalloc", "rpassword"]

[dependencies]
bs58 = "0.4.0"
curve25519-dalek = { git = "https://github.com/codahale/curve25519-dalek", branch = "updated-deps" }
rand = { version = "0.8.5", features = ["min_const_gen"] }
subtle = "2.4.1"
thiserror = "1.0.30"
unicode-normalization = "0.1.19"
xoodyak = "0.7.3"
zeroize = { version = "1.5.3", features = ["derive"] }

# cli-only deps
anyhow = { version = "1.0.55", optional = true }
clap = { version = "3.1.3", features = ["derive"], optional = true }
clap_complete = { version = "3.1.0", optional = true }
clio = { version = "0.2.0", optional = true }
mimalloc = { version = "0.1.28", optional = true }
rpassword = { version = "5.0.1", optional = true }

[dev-dependencies]
criterion = { version = "0.3.5", features = ["html_reports"] }
duct = "0.13.5"
tempfile = "3.3.0"

[[bench]]
name = "benches"
path = "benches/benches.rs"
harness = false

[[bin]]
name = "veil"
required-features = ["cli"]

[profile.release]
codegen-units = 1
lto = "fat"
strip = true
