[workspace]
members = ["veil", "veil-cli", "xtask"]
resolver = "2"

[profile.release]
codegen-units = 1
lto = "fat"

[profile.dev.package.p256]
opt-level = 3

[profile.dev.package.aes]
opt-level = 3

[profile.dev.package.sha2]
opt-level = 3
