[package]
name = "veil"
version = "0.1.0"
authors = ["Coda Hale <coda.hale@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
include = ["src/**/*", "LICENSE-MIT", "LICENSE-APACHE", "README.md"]
description = "Stupid crypto tricks."

[features]
default = []
cli = ["anyhow", "clap", "clap_complete", "clio", "mimalloc", "rpassword"]

[dependencies]
bs58 = "0.4"
curve25519-dalek = "4.0.0-pre.1"
rand = "0.8"
secrecy = "0.8"
thiserror = "1"
unicode-normalization = "0.1"
xoodyak = "0.7"

# cli-only deps
anyhow = { version = "1", optional = true }
clap = { version = "3", features = ["derive"], optional = true }
clap_complete = { version = "3", optional = true }
clio = { version = "0.1", optional = true }
mimalloc = { version = "0.1", optional = true }
rpassword = { version = "5", optional = true }

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }
duct = "0.13"
tempfile = "3"

[[bench]]
name = "benches"
path = "benches/benches.rs"
harness = false

[[bin]]
name = "veil"
required-features = ["cli"]
