[config]
skip_core_tasks = true

[tasks.default]
dependencies = ["fmt", "build", "test", "clippy"]

[tasks.fmt]
command = "cargo"
args = ["fmt"]

[tasks.build]
command = "cargo"
args = ["build", "--all-targets", "--all-features"]

[tasks.test]
command = "cargo"
args = ["test", "--all-features"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all-features", "--tests", "--benches"]