[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
clap = { version = "4.0.11", features = ["deprecated", "derive"] }
xshell = "0.2.2"

[[bin]]
name = "xtask"
path = "src/xtask.rs"
