[package]
name = "xtask"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.77"
clap = { version = "4.4.11", features = ["deprecated", "derive"] }
xshell = "0.2.5"

[[bin]]
name = "xtask"
path = "src/xtask.rs"

[package.metadata.release]
release = false
