[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.3.19", features = ["deprecated", "derive"] }
xshell = "0.2.5"

[[bin]]
name = "xtask"
path = "src/xtask.rs"
