[package]
name = "veil-tool"
version = "0.1.0"
authors = ["Coda Hale <coda.hale@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
argh = "0.1"
clio = "0.1"
filedescriptor = "0.7"
rpassword = "5"
veil = { version = "0.1.0", path = "../veil" }
