[package]
name = "veil"
version = "0.1.0"
authors = ["Coda Hale <coda.hale@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
include = ["src/**/*", "../LICENSE-MIT", "../LICENSE-APACHE", "../README.md"]
description = "Stupid crypto tricks."

[dependencies]
bs58 = "0.5.0"
lockstitch = "0.16.1"
p256 = { version = "0.13.2", default-features = false, features = ["arithmetic", "std", "hash2curve"] }
rand = { version = "0.8.5", features = ["min_const_gen"] }
sha2 = "0.10.8"
subtle = "2.5.0"
thiserror = "1.0.50"

[dev-dependencies]
assert_matches = "1.5.0"
divan = "0.1.0"
expect-test = "1.4.1"
rand_chacha = "0.3.1"

[[bench]]
name = "benches"
path = "benches/benches.rs"
harness = false
