[package]
name = "veil"
version = "0.1.0"
authors = ["Coda Hale <coda.hale@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2"
rand = "0.7"
rand_core = "0.5"
rpassword = "5"
veil-lib = { path = "../veil-lib" }
