[package]
name = "veil"
version = "0.1.0"
authors = ["Coda Hale <coda.hale@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
include = ["src/**/*", "../LICENSE-MIT", "../LICENSE-APACHE", "../README.md"]
description = "Stupid crypto tricks."

[dependencies]
arrayref = "0.3.7"
bs58 = "0.5.1"
ed25519-dalek = { version = "2.1.1", features = ["digest", "hazmat"] }
fips204 = { version = "0.1.1", default-features = false, features = ["ml-dsa-65"] }
lockstitch = "0.25.1"
ml-kem = "0.1.0-alpha"
rand = { version = "0.8.5", features = ["min_const_gen"] }
thiserror = "1.0.58"
x25519-dalek = { version = "2.0.1", features = ["static_secrets"] }

[dev-dependencies]
assert_matches = "1.5.0"
bolero = "0.10.1"
expect-test = "1.4.1"
rand_chacha = "0.3.1"

[lints]
workspace = true
