[package]
name = "veil"
version = "0.1.0"
authors = ["Coda Hale <coda.hale@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
include = ["src/**/*", "../LICENSE-MIT", "../LICENSE-APACHE", "../README.md"]
description = "Stupid crypto tricks."

[dependencies]
bs58 = "0.4.0"
constant_time_eq = "0.2.4"
curve25519-dalek = { version = "4.0.0-pre.5", default-features = false, features = ["alloc", "rand_core"] }
lockstitch = "0.7.2"
rand = { version = "0.8.5", features = ["min_const_gen"] }
thiserror = "1.0.38"

[dev-dependencies]
assert_matches = "1.5.0"
criterion = { version = "0.4.0", features = ["html_reports"] }
expect-test = "1.4.0"
rand_chacha = "0.3.1"

[[bench]]
name = "benches"
path = "benches/benches.rs"
harness = false
