[book]
authors = ["Coda Hale"]
language = "en"
multilingual = false
src = "src"
title = "Veil Cryptosystem"

[preprocessor.katex]
macros = "latex.txt"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[build]
build-dir = "../target/book"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
