[package]
name = "benchmarks"
version = "0.0.0"
publish = false
edition = "2024"

[dependencies]
criterion = "0.5.1"
rand = "0.8.5"
rand_chacha = "0.3.1"
veil = { path = "../veil" }

[[bench]]
name = "benchmarks"
path = "benches/benchmarks.rs"
harness = false

[lints]
workspace = true
